name: 友链申请
description: "A template helps you commit your own website quickly"
labels: ["友链申请"]
body:
  - type: checkboxes
    attributes:
      label: 站点要求
      description: "请确保贵站符合以下要求"
      options:
        - label: 提交申请时处于可用状态
          required: true
        - label: 不涉政、黄、赌、毒
          required: true
  - type: textarea
    attributes:
      label: 站点信息
      description: "照模板填写贵站信息"
      value: |
        title: "站点标题",
        imgurl: "站点图标",
        desc: "站点描述",
        siteurl: "站点链接",
      render: yaml
    validations:
      required: true
  - type: input
    attributes:
      label: 站点友链页面
      description: "能够在贵站看到本站友链信息的页面"
      value: |
        https://
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > - 站长可能因某些原因（睡觉、上学、吃席…）未能及时添加贵站友链信息，但不会装看不见🤫
        > - 请确保您的站点处于**可用**状态。站长偶尔会访问贵站，若遇**无法访问**的情况，您的站点会被打上`失联`标签，直至您的站点恢复正常🥰
        > - 请勿单方面友链，站长发现将会**删除您的友链**😠
        > - 若站长已好回复您的议题，但是仍找不到贵站的友链信息❓
        >   1. 站点构建中…
        >      *耐心等待…*
        >   2. 站点因错误配置导致构建失败
        >      *耐心等待站长修复错误并重新构建站点*
        >   3. 站点因不可抗拒因素导致构建失败
        >      *没招了☠️*
